environment: development

logging:
  file:
    name: logs/marketplace-dev.log
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO
    org.springframework: ERROR
    com.depaul.depaulmarketplace: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:marketplace
  jpa:
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
