#Be sure to change volumn location
#start:   docker-compose up -d
#stop:    docker-compse down

version: "3.8"

services:
  app:
    container_name: marketplaceappp
    image: marketplaceapps
    env_file: ./.env
    ports:
      - "$SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT"
